services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

    runtime: nvidia
    restart: always
    networks:
      - infobroadcaster

volumes:
  ollama:

networks:
  infobroadcaster:
    external: true
    name: infobroadcaster
